### ISSUE TITLE
progress pdk installation on server

### ISSUE THREAD

**Issue by vincentvanhees** [Filter-Bubble/Filter-Bubble-Docker#1]
Derived from: https://passivedatakit.org/getting-started/django-server

- [ ] 1. Check system requirements [mostly following this tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-14-04).
  - [x] Install pip and postgresq
  - [x] create database, database user, and postgis extension
  - [x] install Django with virtualenv
  - [x] Configure
  - [x] Migrate
  - [x] Edit settings.py and urls.py file according to [link](https://github.com/Filter-Bubble/pdk-try-out/blob/master/installation.md).
  - [x] Resolve issues with local connection.
- [ ] 2. Installing Passive Data Kit
  - [x]  Clone the PDK repository to the virtual environment inside the Django installation.
  - [x]  Install Passive Data Kit's Python dependencies, and check that it is available in python.
  - [x] Enable Passive Data Kit in your settings.py.
  - [x] Add PDK routes to your server's urls.py
  - [ ] install the PDK object schema into your database
  - [ ]  import static assets.
- [ ] 3. Configuring Passive Data Kit
- [ ] 4. Setting Up Timed Maintenance Tasks
- [ ] 5. Relevant Server URLs

I am keeping a more elaborate list of notes and action steps in: https://github.com/Filter-Bubble/pdk-try-out/blob/master/installation.md

**Comment by vincentvanhees** [comment]
I have progressed to https://passivedatakit.org/getting-started/django-server at point:

```
Install PDK objects schema (command line):
./manage.py migrate
and get the error:
```

When I am inside Python and do `import django.passive_data_kit` the passive data kit seems to load fine.
However, when I do the step `./manage.py migrate` I get the error 

```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lbogaardt/myproject/myprojectenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/lbogaardt/myproject/myprojectenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/lbogaardt/myproject/myprojectenv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/lbogaardt/myproject/myprojectenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/lbogaardt/myproject/myprojectenv/local/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named passive_data_kit.apps

```

**Comment by vincentvanhees** [comment]
I re-did all the steps with Python 3.6 instead of 2.7.
When I do pip install -r passive_data_kit/requirements.txt:

```
Could not find a version that satisfies the requirement futures==3.2.0 (from -r passive_data_kit/requirements.txt (line 14)) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
No matching distribution found for futures==3.2.0 (from -r passive_data_kit/requirements.txt (line 14))

```
I then installed the previous version of futures with pip.

Next, I did: ./manage.py migrate (same result for `python manage.py migrate`), I get:
```
./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lbogaardt/myproject/pdkenvpython3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/lbogaardt/myproject/pdkenvpython3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/lbogaardt/myproject/pdkenvpython3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/lbogaardt/myproject/pdkenvpython3/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/lbogaardt/myproject/pdkenvpython3/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/lbogaardt/myproject/pdkenvpython3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'passive_data_kit'
```

While if I cd to the django installation folder passive_data_kit is available in Python

**Comment by lbogaardt** [comment]
The Passive Data Kit was in the wrong location. It should be part of the 'myproject' directory, next to the 'manage.py'. I deleted the old directory and cloned a new version in the correct location using git.

There is now a new error (related to PostGIS; I used 'django.contrib.gis.db.backends.postgis' but you use 'django.db.backends.postgresql_psycopg2') but this issue can be closed.

**Comment by vincentvanhees** [comment]
ok, then the instruction "cd /path/to/django" in section 2 of https://passivedatakit.org/getting-started/django-server is incorrect. Maybe we can give that as feedback to Chris
